console.log(document.querySelector(".box"))
console.log(document.querySelector(".box").innerHTML = "Hey Harry")
console.log(document.querySelector(".container").outerHTML)
console.log(document.querySelector(".container").hidden)
console.log(document.querySelector(".container").hasAttribute("style"))